-- local hover_time = 500
-- local hover_timer = nil
-- vim.o.mousemoveevent = true
-- 
-- vim.keymap.set({'', 'i'}, '<MouseMove>', function()
--   if hover_timer then
--     hover_timer:close()
--   end
--   hover_timer = vim.defer_fn(function()
--     hover_timer = nil
--     print('Hover' .. vim.loop.now())
--   end, hover_time)
--   return '<MouseMove>'
-- end, {expr = true})

